# Generated by Django 3.2.5 on 2021-07-31 07:29

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookPDF',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='Books/'), upload_to='static/Books/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='Books/'), upload_to='static/Books/'),
        ),
    ]
