# Generated by Django 3.2.5 on 2021-07-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_auto_20210731_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isIssued',
            field=models.BooleanField(default=False),
        ),
    ]
