# Generated by Django 3.2.5 on 2021-07-31 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Books', '0003_book_isissued'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='issuedTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issuedBooks', to=settings.AUTH_USER_MODEL),
        ),
    ]
