# Generated by Django 3.2.5 on 2021-07-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_book_issuedto'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='dateIssued',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='book',
            name='dateReturned',
            field=models.DateField(auto_now=True),
        ),
    ]
