# Generated by Django 3.2.5 on 2021-07-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_auto_20210731_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='dateIssued',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='dateReturned',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
